test:
  name: medical-consent-benchmark
  description: A benchmark for the medical consent chaincode.
  workers:
    type: local
    number: 1
  rounds:
    - label: createPatientRecord
      description: Create patient records
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/scenario/simple/medical-consent/createPatientRecord.js
        arguments: {}
    - label: getRecordById
      description: Get patient records by ID
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/scenario/simple/medical-consent/getRecordById.js
        arguments: {}
